spring.application.name=ecommerce-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=ecommerce
spring.datasource.password=ecommerce

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=true
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
